### ISSUE TITLE
Cleaning registry leftover error

### ISSUE THREAD

**Issue by maruf8** [map220v/MiPad5-Drivers#11]
I face this error while offline update. please tell me what is wrong here. 

```bash
[17:22:56][Information] DriverUpdater 2.1.1.0 - Cleans and Installs a new set of drivers onto a Windows Image
[17:22:56][Information] Copyright (c) 2017-2023, The LumiaWOA and DuoWOA Authors
[17:22:56][Information] https://github.com/WOA-Project/DriverUpdater

[17:22:56][Information] This program comes with ABSOLUTELY NO WARRANTY.
[17:22:56][Information] This is free software, and you are welcome to redistribute it under certain conditions.

The operation completed successfully.
The operation completed successfully.
[17:22:59][Information] Resealing image to PnP FirstBootUx...
[17:22:59][Information] The device has already been booted once. Reinstalling Board Support Package.
[17:23:18][Information] Enumerating existing drivers...
[17:23:22][Information] Uninstalling drivers...
[17:23:23][Information] [===========================100%===========================] 00:00:00.0
[17:23:23][Information] Fixing potential registry left overs
[17:23:23][Information] Processing SYSTEM hive
[17:23:27][Information] Deleting ControlSet001\Control\DeviceClasses\{3abf6f2d-71c4-462a-8a92-1e6861e6af27}\##?#ACPI#QCOM0575#1#{3abf6f2d-71c4-462a-8a92-1e6861e6af27}
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05D2\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0519\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\5
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\6
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\7
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\d
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\e
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\f
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050A\10
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0533\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM051B\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055F\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM059B\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM059B\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050B\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0576\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050C\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM050D\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05A2\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0593\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0593\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0593\2
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05AE\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05AA\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0561\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05A1\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0507\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0508\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0577\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055F\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05A8\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05CF\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05A7\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0518\d
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0518\12
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0511\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0511\5
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0511\8
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\VEN_QCOM&DEV_058C&SUBSYS_MTP08150&REV_0002\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\VEN_QCOM&DEV_0509&SUBSYS_MTP08150&REV_0002\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0583\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0581\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055A\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0575\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055C\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055C\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055D\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055D\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM059D\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0550\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM059E\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM054E\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM054C\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM055E\64
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0527\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM052E\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0530\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM05CE\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM057F\2&daba3ff&0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0535\1b
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0512\0
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0512\1
[17:23:30][Information] Deleting ControlSet001\Control\DeviceContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\BaseContainers\{00000000-0000-0000-FFFF-FFFFFFFFFFFF}\ACPI\QCOM0512\2
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0507
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0508
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM050A
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM050B
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM050C
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM050D
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0511
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0512
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0518
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0519
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM051B
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0527
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM052E
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0530
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0533
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0535
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM054C
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM054E
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0550
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM055A
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM055C
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM055D
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM055E
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM055F
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0561
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0575
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0576
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0577
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM057F
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0581
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0583
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM0593
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM059B
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM059D
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM059E
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05A1
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05A2
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05A7
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05A8
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05AA
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05AE
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05CE
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05CF
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\QCOM05D2
[17:23:58][Information] Deleting ACPI\VEN_QCOM&DEV_24A5&SUBSYS_MTP08150 in ControlSet001\Enum\ACPI\QCOM24A5\0\HardwareID
[17:23:58][Information] Deleting ACPI\VEN_QCOM&DEV_24A5 in ControlSet001\Enum\ACPI\QCOM24A5\0\CompatibleIDs
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\VEN_QCOM&DEV_0509&SUBSYS_MTP08150&REV_0002
[17:23:58][Information] Deleting ControlSet001\Enum\ACPI\VEN_QCOM&DEV_058C&SUBSYS_MTP08150&REV_0002
[17:24:41][Information] Processing SOFTWARE hive
[17:28:33][Information] Reading definition file...
[17:28:34][Information] Installing new drivers...
[17:28:49][Information] [=====                       10%                           ] 00:02:09.6
[17:28:49][   Error   ] DismApi->AddDriver: ntStatus=0x80070570, driverInf=D:\MiPad5-Drivers-Desktop_2\components\QC8150\Device\DEVICE.SOC_QC8150.NABU\Drivers\Audio\AudMiniport\MiPad5_audmini.inf
[17:30:29][Information] [===========================100%===========================] 00:00:00.0
[17:30:30][Information] Fixing potential registry left overs
[17:30:30][   Error   ] Something happened!
[17:30:30][   Error   ] System.IO.IOException: The file or directory is corrupted and unreadable. : 'H:\Windows\System32\DriverStore\FileRepository\mipad5_audmini.inf_arm64_870ef61190754738'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at DriverUpdater.RegistryFixer.<>c.<FixRegistryPaths>b__4_0(String x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at DriverUpdater.RegistryFixer.FixRegistryPaths(String DrivePath)
   at DriverUpdater.Program.DriverUpdaterAction(String Definition, String DriverRepo, String DevicePart)
[17:30:30][Information] Done!
[17:30:30][Information] Press any key to exit.

```

**Comment by map220v** [comment]
While installing audmini driver it failed with error 0x80070570(The file or directory is corrupted and unreadable) and cleanup failed again with the same error, check if you have good USB connection while updating drivers, if you still get the same error then your Windows installation or driver store is broken, and to fix it you need to reinstall Windows.
